replicaCount: 2

image:
  repository: ghcr.io/vlrrbn/kubernetes-gitops-reliability-platform
  tag: sha-03486a635ddddd4c31a30707344403cdaf512db9
  digest: sha256:917e7e074887af03d25d8282011215705cd2c7afe34eef0f992ddfe762b96917
  pullPolicy: IfNotPresent

fault:
  delayMilliseconds: 0
  errorRate: 0
  ready: true

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
