replicaCount: 2

image:
  repository: ghcr.io/vlrrbn/kubernetes-gitops-reliability-platform
  tag: sha-2a5bb6271cb70fd224997241b890e5e42eb029bc
  digest: sha256:671788b8087031cf1bbd9bb0d57c7453ff6ffbee1249a2dc3c99cafefb67c660
  pullPolicy: IfNotPresent

fault:
  delayMilliseconds: 0
  errorRate: 0
  ready: true

metrics:
  serviceMonitor:
    enabled: true

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
