replicaCount: 2

image:
  repository: ghcr.io/vlrrbn/kubernetes-gitops-reliability-platform
  tag: sha-3403c1ed717443876f580f7cc01f5defba357416
  digest: sha256:bf33556791c27f6b4cad43840eaaa02eb989dbe7623f18a5b101c4b957b8fe54
  pullPolicy: IfNotPresent

fault:
  delayMilliseconds: 0
  errorRate: 0
  ready: true

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
