replicaCount: 2

image:
  repository: ghcr.io/vlrrbn/reliability-demo
  tag: stage-placeholder
  digest: ""
  pullPolicy: IfNotPresent

fault:
  delayMilliseconds: 0
  errorRate: 0
  ready: true

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 250m
    memory: 64Mi
