replicaCount: 2

image:
  repository: ghcr.io/vlrrbn/kubernetes-gitops-reliability-platform
  tag: sha-96201f3b7aca24bd6781889911588f10a63c0a17
  digest: sha256:2b3fb9dd442fe6fc24ff9b3c47f7678cf5593f5fdf9b123b74b83cbac557e8d7
  pullPolicy: IfNotPresent

fault:
  delayMilliseconds: 0
  errorRate: 0
  ready: true

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 250m
    memory: 64Mi
