{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "reliability-demo.fullname" . }}
  labels:
    {{- include "reliability-demo.labels" . | nindent 4 }}
    observability.reliability-platform.io/monitor: "true"
spec:
  selector:
    matchLabels:
      {{- include "reliability-demo.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path | quote }}
      interval: {{ .Values.metrics.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout | quote }}
      scheme: http
      honorLabels: false
{{- end }}
